meta:

name: (( grab meta.name ))


compilation:
  workers: 6
  network: postgresql_docker1
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: postgresql_docker1
    stemcell: (( grab meta.stemcell ))
